### ISSUE TITLE
Issue with inventory

### ISSUE THREAD

**Issue by tl87** [ansible-collections/vmware.vmware#135]
##### SUMMARY
I'm using vmware.vmware.vms as a plugin for an Ansible inventory.

If I'm using the command `ansible-inventory` it works fine, but if I want to use a playbook it fails.

**Some information has been redacted**!

The inventory:

```yaml
plugin: vmware.vmware.vms
hostname: vcenter-url.domain.tld
username: ansible-user
password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  3963...
validate_certs: false

properties:
  - config.name
  - summary.runtime.powerState

groups:
  powered_on_vms: "summary.runtime.powerState == 'poweredOn'"

hostnames:
  - config.name

compose:
    ansible_port: "'5985'"
    ansible_connection: "'winrm'"
    ansible_winrm_transport: "'kerberos'"
    ansible_winrm_server_cert_validation: "'ignore'"
    ansible_winrm_kerberos_delegation: "'true'"
    ansible_winrm_scheme: "'http'"
    ansible_user: "'ANSIBLE-USER@DOMAIN.TLD'"
    ansible_password: "'!vault |
          $ANSIBLE_VAULT;1.1;AES256
          3963...'"
    ansible_host: "'config.name'"
```

I have confirmed that user (ansible-user) has access to VMware and the correct permissions, otherwise I would get this error:

```bash
Unable to log on to the vCenter or ESXi API at vcenter-url.domain.tld:443 as ansible-user: Cannot complete login due to an incorrect user name or password.
```

The ansible-user, can connect to the Windows host, that I am testing with, so I know username and password are correct.

I've also tested the user with `kinit`, and here is output from `klist`:

```bash
(ansible-python-3.13) ansible-user@902f09a50a8d:~$ klist
Ticket cache: FILE:/tmp/krb5cc_1000
Default principal: ANSIBLE-USER@DOMAIN.TLD

Valid starting     Expires            Service principal
03/06/25 13:08:10  03/06/25 23:08:10  krbtgt/DOMAIN.TLD@DOMAIN.TLD
        renew until 03/06/25 23:08:10
```

The output I get is:

```bash
PLAY [Ping Windows hosts] *******************************************************************************
[WARNING]: Found variable using reserved name: name

TASK [Ping all Windows hosts] ***************************************************************************
fatal: [my-test-host.domain.tld]: UNREACHABLE! => {"changed": false, "msg": "Kerberos auth failure for principal ANSIBLE-USER@DOMAIN.TLD with pexpect: kinit: Password incorrect while getting initial credentials", "unreachable": true}

PLAY RECAP **********************************************************************************************
my-test-host.domain.tld      : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
```

Just be extra sure that the ansible user is working, I tried with a static inventory:

```yaml
HOSTS:
  vars:
    ansible_port: 5985
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_kerberos_delegation: true
    ansible_winrm_scheme: http
    ansible_user: ANSIBLE-USER@DOMAIN.TLD
    ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          3963...
  hosts:
    my-test-host.domain.tld:
```

Playbook looks like this:

```yaml
---
- name: Ping Windows hosts
  hosts: all
  gather_facts: false
  tasks:
    - name: Ping all Windows hosts
      ansible.windows.win_ping:
      async: 10
      poll: 0
```

I get this output:

```bash
PLAY [Ping Windows hosts] *******************************************************************************

TASK [Ping all Windows hosts] ***************************************************************************
ok: [my-test-host.domain.tld] => {"ansible_async_watchdog_pid": 11076, "ansible_job_id": "j18214740639.10560", "changed": false, "finished": 0, "results_file": "C:\\Users\\ansible-user\\.ansible_async\\j18214740639.10560", "started": 1}

PLAY RECAP **********************************************************************************************
my-test-host.domain.tld      : ok=1    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=
```

WinRM is setup on the remote Windows host (https://docs.ansible.com/ansible/latest/os_guide/windows_winrm.html#windows-winrm)

##### ISSUE TYPE
- Bug Report or I might be missing an option?

##### COMPONENT NAME
vmware.vmware.vms

##### ANSIBLE VERSION
```paste below
ansible [core 2.18.3]
  config file = None
  configured module search path = ['/home/ansible-user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/ansible-user/.local/lib/python3.13/site-packages/ansible
  ansible collection location = /home/ansible-user/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/ansible-user/.local/bin/ansible
  python version = 3.13.2 | packaged by conda-forge | (main, Feb 17 2025, 14:10:22) [GCC 13.3.0] (/home/ansible-user/.conda/envs/ansible-python-3.13/bin/python3.13)
  jinja version = 3.1.5
  libyaml = True
```

##### COLLECTION VERSION
```paste below
Collection           Version
-------------------- -------
ansible.netcommon    7.1.0
ansible.posix        2.0.0
ansible.utils        5.1.2
ansible.windows      2.7.0
community.general    10.4.0
community.mysql      3.12.0
community.postgresql 3.11.0
community.vmware     5.4.0
community.windows    2.3.0
community.zabbix     3.3.0
microsoft.ad         1.8.0
vmware.vmware        1.10.1
```

##### CONFIGURATION
```paste below
ANSIBLE_PIPELINING(/home/ansible-user/ansible/ansible.cfg) = True
COLOR_CHANGED(/home/ansible-user/ansible/ansible.cfg) = yellow
COLOR_DEBUG(/home/ansible-user/ansible/ansible.cfg) = dark gray
COLOR_DEPRECATE(/home/ansible-user/ansible/ansible.cfg) = purple
COLOR_DIFF_ADD(/home/ansible-user/ansible/ansible.cfg) = green
COLOR_DIFF_LINES(/home/ansible-user/ansible/ansible.cfg) = cyan
COLOR_DIFF_REMOVE(/home/ansible-user/ansible/ansible.cfg) = red
COLOR_ERROR(/home/ansible-user/ansible/ansible.cfg) = red
COLOR_HIGHLIGHT(/home/ansible-user/ansible/ansible.cfg) = white
COLOR_OK(/home/ansible-user/ansible/ansible.cfg) = green
COLOR_SKIP(/home/ansible-user/ansible/ansible.cfg) = cyan
COLOR_UNREACHABLE(/home/ansible-user/ansible/ansible.cfg) = red
COLOR_VERBOSE(/home/ansible-user/ansible/ansible.cfg) = blue
COLOR_WARN(/home/ansible-user/ansible/ansible.cfg) = bright purple
CONFIG_FILE() = /home/ansible-user/ansible/ansible.cfg
DEFAULT_LOAD_CALLBACK_PLUGINS(/home/ansible-user/ansible/ansible.cfg) = True
DEFAULT_REMOTE_USER(/home/ansible-user/ansible/ansible.cfg) = root
DEFAULT_STDOUT_CALLBACK(/home/ansible-user/ansible/ansible.cfg) = yaml
DEFAULT_TIMEOUT(/home/ansible-user/ansible/ansible.cfg) = 10
DEFAULT_VAULT_PASSWORD_FILE(/home/ansible-user/ansible/ansible.cfg) = /home/ansible-user/ansible>
DIFF_ALWAYS(/home/ansible-user/ansible/ansible.cfg) = True
```

##### OS / ENVIRONMENT
```
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

##### STEPS TO REPRODUCE
See SUMMARY

##### EXPECTED RESULTS
I was hoping to be able to use VMware as an inventory source, so I don't have to manually add or remove hosts from the inventory, because the Inventory is dynamically pulled from VMware.

##### ACTUAL RESULTS
Somehow, even though I know that kerberos authentictaion is working, it does not seem to be that case, when trying to run a playbook, but getting the inventory with `ansible-inventory` work perfectly.

**Comment by mikemorency** [comment]
My guess is that the `ansible_password` is being evaluated as a string instead of an encrypted vault string because its quoted. I will try to reproduce, but it might be a bit.

You can try messing around with the quotes in your inventory.
Or, one other solution I can think of is to put your hosts in a group, possible `connection_windows`, using the inventory. Then, have a group_vars file that assigns the variables you want. Your project structure would look like:
```
my_inventory.vms.yml
group_vars/
  connection_windows.yml
```
and `connection_windows.yml` would look like
```
ansible_port: 5985
ansible_connection: winrm
ansible_winrm_transport: kerberos
ansible_winrm_server_cert_validation: ignore
ansible_winrm_kerberos_delegation: true
ansible_winrm_scheme: http
ansible_user: ANSIBLE-USER@DOMAIN.TLD
ansible_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      3963...
```

**Comment by tl87** [comment]
Thank you for the replies and being so helpful.

I've played around with quotes, like you mentioned and below is my results.

## With only ":

```yaml
compose:
    ansible_port: "5985"
    ansible_connection: "winrm"
    ansible_winrm_transport: "kerberos"
    ansible_winrm_server_cert_validation: "ignore"
    ansible_winrm_kerberos_delegation: "true"
    ansible_winrm_scheme: "http"
    ansible_user: "ANSIBLE-USER@DOMAIN.TLD"
    ansible_password: "!vault |
          $ANSIBLE_VAULT;1.1;AES256
          3963..."
    ansible_host: "config.name"
```

I get:

```bash
TASK [Ping all Windows hosts] ******************************************************************************************************************************************************
fatal: [my-test-host.domain.tld]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: OpenSSH_9.2p1 Debian-2+deb12u5, OpenSSL 3.0.15 3 Sep 2024\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files\r\ndebug1: /etc/ssh/ssh_config line 21: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/home/ansible-user/.ansible/cp/4db80590f2\" does not exist....Connection closed by x.x.x.x port 5985", "unreachable": true}
```

It seems like it's trying to connect to my Windows test host via SSH, even though `compose` has `ansible_connection: "winrm"`.

## With out any " or '

```yaml
compose:
    ansible_port: 5985
    ansible_connection: winrm
    ansible_winrm_transport: kerberos
    ansible_winrm_server_cert_validation: ignore
    ansible_winrm_kerberos_delegation: true
    ansible_winrm_scheme: http
    ansible_user: ANSIBLE-USER@DOMAIN.TLD
    ansible_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          3963...
    ansible_host: config.name
```

It's basically the same as with ":

```bash
TASK [Ping all Windows hosts] ******************************************************************************************************************************************************
fatal: [my-test-host.domain.tld]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: OpenSSH_9.2p1 Debian-2+deb12u5, OpenSSL 3.0.15 3 Sep 2024\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf....
```

## With only '

```yaml
compose:
    ansible_port: '5985'
    ansible_connection: 'winrm'
    ansible_winrm_transport: 'kerberos'
    ansible_winrm_server_cert_validation: 'ignore'
    ansible_winrm_kerberos_delegation: 'true'
    ansible_winrm_scheme: 'http'
    ansible_user: 'ANSIBLE-USER@DOMAIN.TLD'
    ansible_password: '!vault |
          $ANSIBLE_VAULT;1.1;AES256
          3963...'
    ansible_host: 'config.name'
```

I get:

```bash
Using inventory plugin 'ansible_collections.vmware.vmware.plugins.inventory.vms' to process inventory source '/home/ansible-user/vmware_vms.yaml'
[WARNING]:  * Failed to parse /home/'ansible-user/vmware_vms.yaml with auto plugin: (vmodl.fault.ManagedObjectNotFound) {    dynamicType = <unset>,    dynamicProperty =
(vmodl.DynamicProperty) [],    msg = "The object 'vim.VirtualMachine:vm-2957349' has already been deleted or has not been completely created",    faultCause = <unset>,
faultMessage = (vmodl.LocalizableMessage) [],    obj = 'vim.VirtualMachine:vm-2957349' }
[WARNING]:  * Failed to parse /home/'ansible-user/vmware_vms.yaml with yaml plugin: Plugin configuration YAML file, not YAML inventory
[WARNING]:  * Failed to parse /home/'ansible-user/vmware_vms.yaml with ini plugin: Invalid host pattern 'plugin:' supplied, ending in ':' is not allowed, this character is
reserved to provide a port.
[WARNING]: Unable to parse /home/'ansible-user/vmware_vms.yaml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [Ping Windows hosts] **********************************************************************************************************************************************************
skipping: no hosts matched
```

I've tried with `"'`, `"`, `'` and ` `. It seems like compose just uses default vaules, presumably SSH.

## Tring the jinja temlpate approach

File structure:

```bash
ansible
├── inventory
│   ├── vmware_vms.yaml
│   ├── group_vars
│   │   └── connection_windows.yml
```

connection_windows.yaml has:

```yaml
ansible_port: 5985
ansible_connection: winrm
ansible_winrm_transport: kerberos
ansible_winrm_server_cert_validation: ignore
ansible_winrm_kerberos_delegation: true
ansible_winrm_scheme: http
ansible_user: ANSIBLE-USER@DOMAIN.TLD
ansible_password: !vault |
      $ANSIBLE_VAULT;1.1;AES256
      3963...
```

vmware_vms.yaml:

```yaml
plugin: vmware.vmware.vms
hostname: vcenter-url.domain.tld
username: ansible-user
password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  396..
validate_certs: false

properties:
  - config.name
  - summary.runtime.powerState

groups:
  powered_on_vms: "summary.runtime.powerState == 'poweredOn'"

hostnames:
  - config.name

compose:
    ansible_port: "'{{ ansible_port }}'"
    ansible_connection: "'{{ ansible_connection }}'"
    ansible_winrm_transport: "'{{ ansible_winrm_transport }}'"
    ansible_winrm_server_cert_validation: "'{{ ansible_winrm_server_cert_validation }}'"
    ansible_winrm_kerberos_delegation: "'{{ ansible_winrm_kerberos_delegation }}'"
    ansible_winrm_scheme: "'{{ ansible_winrm_scheme }}'"
    ansible_user: "'{{ ansible_user }}'"
    ansible_password: "'{{ ansible_password }}'"
    ansible_host: "'{{ ansible_host }}'"
```

I get below, when trying to run the ping playbook:

```yaml
TASK [Ping all Windows hosts] ******************************************************************************************************************************************************
fatal: [my-test-host.domain.tld]: FAILED! =>
  msg: 'An unhandled exception occurred while templating ''{{ ansible_connection }}''. Error was a <class ''ansible.errors.AnsibleError''>, original message: An unhandled exception occurred while templating ''{{ ansible_connection }}''....
```

Seems like Ansible is having trouble getting the values from `connection_windows.yaml`.

I've also tried removing `'` from `vmware_vms.yaml`:

```yaml
plugin: vmware.vmware.vms
hostname: vcenter-url.domain.tld
username: ansible-user
password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  396..
validate_certs: false

properties:
  - config.name
  - summary.runtime.powerState

groups:
  powered_on_vms: "summary.runtime.powerState == 'poweredOn'"

hostnames:
  - config.name

compose:
    ansible_port: "{{ ansible_port }}"
    ansible_connection: "{{ ansible_connection }}"
    ansible_winrm_transport: "{{ ansible_winrm_transport }}"
    ansible_winrm_server_cert_validation: "{{ ansible_winrm_server_cert_validation }}"
    ansible_winrm_kerberos_delegation: "{{ ansible_winrm_kerberos_delegation }}"
    ansible_winrm_scheme: "{{ ansible_winrm_scheme }}"
    ansible_user: "{{ ansible_user }}"
    ansible_password: "{{ ansible_password }}"
    ansible_host: "{{ ansible_host }}"
```

It gives me:

```bash
TASK [Ping all Windows hosts] ******************************************************************************************************************************************************
fatal: [my-test-host.domain.tld]: UNREACHABLE! => changed=false
  msg: |-
    Failed to connect to the host via ssh: OpenSSH_9.2p1 Debian-2+deb12u5, OpenSSL 3.0.15 3 Sep 2024
    debug1: Reading configuration data /etc/ssh/ssh_config
    debug1: /etc/ssh/ssh_config line 19: include /etc/ssh/ssh_config.d/*.conf matched no files
    debug1: /etc/ssh/ssh_config line 21: Applying options for *
    debug1: resolve_canonicalize: hostname  is an unrecognised address
    debug1: auto-mux: Trying existing master
    debug1: Control socket "/home/ansible-user/.ansible/cp/fd9365fbbc" does not exist
    ssh: Could not resolve hostname : Name or service not known
  unreachable: true
```

Seems like it again defaults to SSH.

Do you have another suggestion or maybe I'm doing something wrong?

Thanks in advance :)

**Comment by tl87** [comment]
With the inventory below:

```yaml
plugin: vmware.vmware.vms
hostname: vcenter-url.domain.tld
username: ansible-user
password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  3963...
validate_certs: false

properties:
  - config.name
  - summary.runtime.powerState

groups:
  powered_on_vms: "summary.runtime.powerState == 'poweredOn'"

hostnames:
  - config.name

compose:
    ansible_port: "'5985'"
    ansible_connection: "'winrm'"
    ansible_winrm_transport: "'kerberos'"
    ansible_winrm_server_cert_validation: "'ignore'"
    ansible_winrm_kerberos_delegation: "'true'"
    ansible_winrm_scheme: "'http'"
    ansible_user: "'ANSIBLE-USER@DOMAIN.TLD'"
    ansible_password: "'{actual password and not as an encrypted string}'"
    ansible_host: "'config.name'"
```

I get this error when using the inventory with my Ping playbook:

```bash
fatal: [my-test-host.domain.tld]: UNREACHABLE! => changed=false
  msg: 'kerberos: Invalid URL ''http://:5985/wsman'': No host supplied'
  unreachable: true
```

Seem like hosts are not parsed, but using `ansible-inventory`-command with the same inventory, as the one above, shows all hosts in VMware.

I don't get it :(

**Comment by mikemorency** [comment]
Ill try to explain with each of your examples:

# With only " (or '):
When using a single set of quotes, the value is evaluated as a jinja pattern. This means for example, 5985 is being evaluated as a variable and not as a string or int. Since 5985 is not a variable, ansible just ignores the whole thing. If you have `strict: True` in the inventory config, I believe an error would be thrown
```
# this is what you tried, doesnt work
ansible_port: "5985"   ->    ansible_port: "{{ 5985 }}"

# this is what you want
ansible_port: "'5985'"   ->    ansible_port: "{{ '5985' }}"
```

# With out any " or '
The issue here is similar to the previous example, in that the value is evaluated as a jinja pattern. But without the explicit quotes, ansible does not know what to do an ignores the whole thing. With `strict: True`, I would expect an error

In both this case and the previous one, the `ansible_connection` variable is not able to be evaluated as jinja and so it is ignored. That is why the playbook is trying to use SSH (the default connection method).

# With only '

In this instance, there is something else at play, unrelated to the compose section. In your playbook/inventory output, there is this line:
```
[WARNING]:  * Failed to parse /home/'ansible-user/vmware_vms.yaml with auto plugin: (vmodl.fault.ManagedObjectNotFound) {    dynamicType = <unset>,    dynamicProperty =
(vmodl.DynamicProperty) [],    msg = "The object 'vim.VirtualMachine:vm-2957349' has already been deleted or has not been completely created",    faultCause = <unset>,
faultMessage = (vmodl.LocalizableMessage) [],    obj = 'vim.VirtualMachine:vm-2957349' }
```
Which says that a VM was modified while the inventory was trying to gather information about it. So the inventory plugin basically never finished and no hosts were passed to the playbook

# Tring the jinja temlpate approach

In this situation, your inventory config file never assigns the hosts to the `connection_winrm` group, which is why they do not get those variables. You should try with the following inventory config:
```
plugin: vmware.vmware.vms
hostname: vcenter-url.domain.tld
username: ansible-user
password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  3963...
validate_certs: false

properties:
  - config.name
  - summary.runtime.powerState

groups:
  # fyi, these are also jinja patterns!
  powered_on_vms: "summary.runtime.powerState == 'poweredOn'"   # this is like "{{ summary.runtime.powerState == 'poweredOn' }}"
  connection_winrm: "True"   # this is like "{{ True }}"

hostnames:
  - config.name

# you dont need any of the compose variables defined here
```

# With the inventory below:
Finally, in your latest post, this line in your `compose` is whats incorrect:
```
ansible_host: "'config.name'"    -> "{{ 'config.name' }}"
```
This should actually be
```
ansible_host: "config.name"    -> "{{ config.name }}"
```
since you want the value of the variable `config.name`, and not the literal string `'config.name'`

**Comment by tl87** [comment]
I've tried removing `ansible_host` in the `compose` section, as you have suggested, unfortunately it does not seem to work.

The inventory looks like:

```yaml
plugin: vmware.vmware.vms
hostname: vcenter-url.domain.tld
username: ansible-user
password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  3963...
validate_certs: false

properties:
  - config.name
  - summary.runtime.powerState

groups:
  powered_on_vms: "summary.runtime.powerState == 'poweredOn'"

hostnames:
  - config.name

compose:
    ansible_port: "'5985'"
    ansible_connection: "'winrm'"
    ansible_winrm_transport: "'kerberos'"
    ansible_winrm_server_cert_validation: "'ignore'"
    ansible_winrm_kerberos_delegation: "'true'"
    ansible_winrm_scheme: "'http'"
    ansible_user: "'ANSIBLE-USER@DOMAIN.TLD'"
    ansible_password: "'actual password and not as an encrypted string'"
```

When using the inventory, with my ping playbook, I see:

```bash
PLAYBOOK: ping.yml 

PLAY [Ping Windows hosts] 
[WARNING]: Found variable using reserved name: name

TASK [Ping all Windows hosts] 
task path: /home/ansible-user/ansible/playbooks/ping.yml:9
Using module file /home/ansible-user/.ansible/collections/ansible_collections/ansible/windows/plugins/modules/win_ping.ps1
Pipelining is enabled.
<> ESTABLISH WINRM CONNECTION FOR USER: ANSIBLE-USER@DOMAIN.TLD on PORT 5985 TO
calling kinit with pexpect for principal ANSIBLE-USER@DOMAIN.TLD
fatal: [my-test-host.domain.tld]: UNREACHABLE! => changed=false
  msg: 'kerberos: Invalid URL ''http://:5985/wsman'': No host supplied'
  unreachable: true

PLAY RECAP
my-test-host.domain.tld      : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0
```

Somehow, hostnames/config.name is not parsed.

If possible, can you please provide an example of an inventory, where compose is used, and ansible_connection is winrm? Or maybe I just need to add, remove or edit some of the options in my inventory, like `properties`, `groups` or maybe `hostnames`.

**Comment by mikemorency** [comment]
Im sorry, you're right. I got confused 😅 

`hostnames` will set the inventory hostname. To modify `ansible_host` you need to use `compose`. This should work for you:
```
hostnames:
  - config.name

compose:
    ansible_port: "'5985'"
    ansible_connection: "'winrm'"
    ansible_winrm_transport: "'kerberos'"
    ansible_winrm_server_cert_validation: "'ignore'"
    ansible_winrm_kerberos_delegation: "'true'"
    ansible_winrm_scheme: "'http'"
    ansible_user: "'ANSIBLE-USER@DOMAIN.TLD'"
    ansible_password: "'actual password and not as an encrypted string'"
    ansible_host: config.name
```

**Comment by mikemorency** [comment]
Not exactly the same, but I was able to connect to a windows host with:
```
---
plugin: vmware.vmware.vms
search_paths:
  - /Eco-Datacenter/vm/mm-test
filter_expressions:
  - name != "mmtest-windows"

properties: ["config.name", "guest.ipAddress"]
hostnames:
  - config.name
compose:
  ansible_port: "'5985'"
  ansible_connection: "'winrm'"
  ansible_winrm_transport: "'ntlm'"
  ansible_winrm_server_cert_validation: "'ignore'"
  ansible_winrm_scheme: "'http'"
  ansible_user: "'Administrator'"
  ansible_password: "'myPassword!'"
  ansible_host: '"10.10.10.10"'
```

```
~/git/vmware.vmware $ ansible -m win_ping -i test.vms.yml  all
mmtest-windows | SUCCESS => {
    "changed": false,
    "ping": "pong"
}
```
