### ISSUE TITLE
Unable to feature tags within keyed_group

### ISSUE THREAD

**Issue by BenjaminDebotte** [ansible-collections/vmware.vmware#170]
##### SUMMARY

We're trying to migrate from `community.vmware` to `vmware.vmware` as we noticed the deprecation warning. Using `keyed_groups` property within `vmware.vmware.vms`, we've been unable to retrieve groups named after our tags. Back when using the `community.vmware` inventory plugins, refering to this https://github.com/ansible-collections/community.vmware/issues/261#issuecomment-649272717, we were able to do so.  

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME

`vmware.vmware.vms inventory plugins`

##### ANSIBLE VERSION

```
ansible [core 2.17.5]
  config file = /home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg
  configured module search path = ['/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/plugins/modules', '/usr/share/ansible']
  ansible python module location = /home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/.venv/lib/python3.11/site-packages/ansible
  ansible collection location = /home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/galaxy_roles
  executable location = /home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/.venv/bin/ansible
  python version = 3.11.9 (main, Sep 23 2024, 11:28:15) [GCC 12.2.0] (/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/.venv/bin/python)
  jinja version = 3.1.4
  libyaml = True

```

##### COLLECTION VERSION

```paste below
# /home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/galaxy_roles/ansible_collections
Collection                               Version
---------------------------------------- -------
ansible.posix                            2.0.0
community.docker                         4.1.0
community.general                        10.1.0
community.vmware                         5.2.0
devsec.hardening                         10.2.0
grafana.grafana                          5.7.0
vmware.vmware                            1.11.0
```

##### CONFIGURATION

```paste below
ANSIBLE_FORCE_COLOR(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = True
ANSIBLE_NOCOWS(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = False
COLLECTIONS_PATHS(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = ['/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/galaxy_roles']
CONFIG_FILE() = /home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg
DEFAULT_ACTION_PLUGIN_PATH(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = ['/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/plugins/action', '/home/bdebotte/.ansible/plugins/action_plugins', '/usr/share/ansible_plugins/action_plugins']
DEFAULT_CALLBACK_PLUGIN_PATH(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = ['/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/plugins/callback', '/home/bdebotte/.ansible/plugins/callback_plugins', '/usr/share/ansible_plugins/callback_plugins']
DEFAULT_CONNECTION_PLUGIN_PATH(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = ['/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/plugins/connection', '/home/bdebotte/.ansible/plugins/connection_plugins', '/usr/share/ansible_plugins/connection_plugins']
DEFAULT_FILTER_PLUGIN_PATH(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = ['/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/plugins/filter', '/home/bdebotte/.ansible/plugins/filter_plugins', '/usr/share/ansible_plugins/filter_plugins']
DEFAULT_FORCE_HANDLERS(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = False
DEFAULT_FORKS(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = 20
DEFAULT_GATHERING(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = smart
DEFAULT_HASH_BEHAVIOUR(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = replace
DEFAULT_HOST_LIST(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = ['/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/inventory/dejamobile']
DEFAULT_INTERNAL_POLL_INTERVAL(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = 0.001
DEFAULT_JINJA2_EXTENSIONS(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = jinja2.ext.do
DEFAULT_LOG_PATH(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = /home/bdebotte/.ansible/ansible.log
DEFAULT_LOOKUP_PLUGIN_PATH(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = ['/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/plugins/lookup', '/home/bdebotte/.ansible/plugins/lookup_plugins', '/usr/share/ansible_plugins/lookup_plugins']
DEFAULT_MANAGED_STR(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = Ansible managed: {{{{ template_path | basename }}}}
DEFAULT_MODULE_PATH(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = ['/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/plugins/modules', '/usr/share/ansible']
DEFAULT_NO_LOG(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = False
DEFAULT_NO_TARGET_SYSLOG(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = True
DEFAULT_POLL_INTERVAL(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = 15
DEFAULT_REMOTE_PORT(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = 22
DEFAULT_REMOTE_USER(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = ansible
DEFAULT_ROLES_PATH(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = ['/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/galaxy_roles', '/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/roles']
DEFAULT_STRATEGY(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = linear
DEFAULT_STRATEGY_PLUGIN_PATH(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = ['/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/plugins/strategy', '/home/bdebotte/.ansible/plugins/strategy_plugins', '/usr/share/ansible_plugins/strategy_plugins']
DEFAULT_TIMEOUT(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = 30
DEFAULT_TRANSPORT(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = ssh
DEFAULT_UNDEFINED_VAR_BEHAVIOR(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = True
DEFAULT_VARS_PLUGIN_PATH(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = ['/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/plugins/vars', '/home/bdebotte/.ansible/plugins/vars_plugins', '/usr/share/ansible_plugins/vars_plugins']
DEFAULT_VAULT_PASSWORD_FILE(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = XXXXXXXX
DISPLAY_ARGS_TO_STDOUT(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = False
DISPLAY_SKIPPED_HOSTS(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = False
EDITOR(env: EDITOR) = nvim
HOST_KEY_CHECKING(env: ANSIBLE_HOST_KEY_CHECKING) = False
INTERPRETER_PYTHON(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = auto
INVENTORY_IGNORE_EXTS(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = ['.pyc', '.pyo', '.swp', '.bak', '~', '.rpm', '.md', '.txt', '~', '.orig', '.retry']
PAGER(env: PAGER) = less
RETRY_FILES_ENABLED(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = True
RETRY_FILES_SAVE_PATH(/home/bdebotte/Documents/projects/dejamobile/devops/iac/infrastructure/ansible.cfg) = /home/bdebotte/.ansible/retry
```

##### OS / ENVIRONMENT

```
Debian GNU/Linux trixie/sid
Python 3.11.9
Package manager: poetry
vsphere-automation-sdk @ https://github.com/vmware/vsphere-automation-sdk-python/archive/refs/tags/v8.0.3.0.tar.gz
```

##### STEPS TO REPRODUCE

Using this configuration named `10-vcenter.vms.yml`

```yaml
---
plugin: vmware.vmware.vms
strict: false
cache: true
cache_timeout: 3600
cache_plugin: ansible.builtin.yaml
cache_connection: .cache/vmware-inventory
hostname: <REDACTED>
username: <REDACTED>
password: <REDACTED>
validate_certs: false
gather_tags: true
flatten_nested_properties: true
filters:
  - runtime.powerState == "poweredOn"
  - "'vc2-' in config.name"
hostnames:
  - config.name
compose:
  ansible_host: guest.ipAddress
  composed_var: config.name
  ansible_connection: "'ssh'"
with_nested_properties: true
keyed_groups:
  - key: tags
  - key: config.guestId
  - key: summary.runtime.powerState
groups:
  vcenter2: true
```

Here is an example of what returns a VM in our inventory cache:

```
vc2-dummy-djm-prod-frcaen-01:
  config:
    cpuHotAddEnabled: false
    cpuHotRemoveEnabled: false
    guestId: ubuntu64Guest
    hardware:
      numCPU: 2
    instanceUuid: X
    name: vc2-dummy-djm-prod-frcaen-01
    template: false
    uuid: X
  customValue: {}
  guest:
    guestId: ubuntu64Guest
    guestState: running
    hostName: vc2-dummy-djm-prod-frcaen-01
    ipAddress: 192.168.100.X
  moid: vm-X
  name: vc2-dummy-djm-prod-frcaen-01
  path: /X/vm/Managed
  runtime:
    maxMemoryUsage: 8192
  summary:
    runtime:
      powerState: poweredOn
  tags:
    urn:vmomi:InventoryServiceTag:70f87e82-6ac6-42bc-878c-817d7b2a4520:GLOBAL: dummy
    urn:vmomi:InventoryServiceTag:bb10e90b-263f-4248-be06-086df1100d6b:GLOBAL: tofu-managed
  tags_by_category:
    app_type:
    - urn:vmomi:InventoryServiceTag:70f87e82-6ac6-42bc-878c-817d7b2a4520:GLOBAL: dummy
    tofu:
    - urn:vmomi:InventoryServiceTag:bb10e90b-263f-4248-be06-086df1100d6b:GLOBAL: tofu-managed
```

##### EXPECTED RESULTS

I expect to have `vc2-dummy-djm-prod-frcaen-01` VM, tagged with `tofu-managed` and `dummy`, to be part of groups `tofu-managed` and `dummy`

##### ACTUAL RESULTS

`ansible-inventory -i inventory/dejamobile --list -l vc2-dummy-djm-prod-frcaen-01`

doesn't return any group expected but doesn't fail.
