### ISSUE TITLE
vmware.vmware.vms inventory plugin performs slowly in an Ansible execution environment

### ISSUE THREAD

**Issue by eddie-jennings** [ansible-collections/vmware.vmware#172]
##### SUMMARY
When utilizing the `vmware.vmware.vms` dynamic inventory plugin within an Ansible execution environment, the plugin takes 5-7x longer to produce an inventory than when used outside of an execution environment.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware.vmware.vms

##### ANSIBLE VERSION

```paste below
ansible [core 2.18.4]
  config file = None
  configured module search path = ['/runner/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.13/site-packages/ansible
  ansible collection location = /runner/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible
  python version = 3.13.2 (main, Feb  4 2025, 00:00:00) [GCC 14.2.1 20250110 (Red Hat 14.2.1-7)] (/usr/bin/python3.13)
  jinja version = 3.1.6
  libyaml = True
```

##### COLLECTION VERSION

```paste below
# /usr/share/ansible/collections/ansible_collections
Collection    Version
------------- -------
vmware.vmware 1.11.0
```

##### CONFIGURATION

```paste below
CONFIG_FILE() = /home/myuser/ansible/ansible.cfg
DEFAULT_BECOME(/home/myuser/ansible/ansible.cfg) = False
DEFAULT_FORKS(/home/myuser/ansible/ansible.cfg) = 100
DEFAULT_HOST_LIST(/home/myuser/ansible/ansible.cfg) = ['/home/myuser/ansible/inventory']
DEFAULT_REMOTE_USER(/home/myuser/ansible/ansible.cfg) = the_remote_user_account
DEFAULT_ROLES_PATH(/home/myuser/ansible/ansible.cfg) = ['/home/myuser/ansible/roles']
DEFAULT_VAULT_PASSWORD_FILE(/home/myuser/ansible/ansible.cfg) = /path/to/the/file
HOST_KEY_CHECKING(/home/myuser/ansible/ansible.cfg) = False
INVENTORY_ENABLED(/home/myuser/ansible/ansible.cfg) = ['vmware.vmware.vms', 'community.vmware.vmware_vm_inventory', >

GALAXY_SERVERS:
```

##### OS / ENVIRONMENT

This is the execution environment build:
```yaml
---
version: 3
images:
  base_image:
    name: quay.io/fedora/fedora-minimal:41-x86_64
dependencies:
  python_interpreter:
    package_system: "python3"
    python_path: "/usr/bin/python3.13"
  ansible_core:
    package_pip: ansible-core
  ansible_runner:
    package_pip: ansible-runner
  galaxy:
    collections:
      - name: ansible.utils
      - name: ansible.posix
      - name: ansible.windows
      - name: community.crypto
      - name: community.general
      - name: community.vmware
      - name: community.windows
      - name: microsoft.ad
      - name: vmware.vmware
  system:
    - git-core
    - sshpass
additional_build_steps:
  append_final:
    - LABEL org.opencontainers.image.source=https://fqdn.of.internal.repo
    - LABEL org.opencontainers.image.description="Internal image description"   
...
```
This is the podman information from the RHEL 9.5 VM that's using this execution environment.

```
Client:       Podman Engine
Version:      5.2.2
API Version:  5.2.2
Go Version:   go1.23.6 (Red Hat 1.23.6-2.el9_5)
Built:        Mon Mar 17 08:03:54 2025
OS/Arch:      linux/amd64
```

##### STEPS TO REPRODUCE

On the RHEL 9.5 VM I run the following command to time.

```
time ansible-navigator inventory -i vmware_vms.yml -m stdout --graph
```
I also test this without the execution environment using:
```
time ansible-inventory -i vmware_vms.yml --graph
```

##### EXPECTED RESULTS

Time results to be between 2 and 3 minutes.  Similar to the results when generating an inventory without using an execution environment.
```
real    2m32.861s
user    0m47.317s
sys     0m5.377s
```

##### ACTUAL RESULTS

When generating the inventory using an execution environment, between 16-18 minutes elapses.

```paste below
[myuser@myvm ansible]$ time ansible-navigator inventory -i vmware_vms.yml -m stdout --graph -vvvv
ansible-inventory [core 2.18.4]
  config file = /home/myuser/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.13/site-packages/ansible
  ansible collection location = /root/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/local/bin/ansible-inventory
  python version = 3.13.2 (main, Feb  4 2025, 00:00:00) [GCC 14.2.1 20250110 (Red Hat 14.2.1-7)] (/usr/bin/python3.13)
  jinja version = 3.1.6
  libyaml = True
Using /home/myuser/ansible/ansible.cfg as config file
setting up inventory plugins
Loading collection vmware.vmware from /usr/share/ansible/collections/ansible_collections/vmware/vmware
Loading collection ansible.builtin from
Loading collection community.vmware from /usr/share/ansible/collections/ansible_collections/community/vmware
[DEPRECATION WARNING]: community.vmware.vmware_vm_inventory has been deprecated. Use vmware.vmware.vms instead. This
feature will be removed from community.vmware in version 7.0.0. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.
Trying secret FileVaultSecret(filename='/path/to/vault/file') for vault_id=default
Trying secret FileVaultSecret(filename='/path/to/vault/file') for vault_id=default
Trying secret FileVaultSecret(filename='/path/to/vault/file') for vault_id=default
Parsed /home/myuser/ansible/vmware_vms.yml inventory source with ansible_collections.vmware.vmware.plugins.inventory.vms plugin
@all:
  |--@ungrouped:
  |--about 180 VMs divided into 3 groups

real    16m34.880s
user    0m1.254s
sys     0m0.730s
```
