### ISSUE TITLE
vmware.vmware.cluster_ha: advanced_settings not working

### ISSUE THREAD

**Issue by pandalec** [ansible-collections/vmware.vmware#190]
##### SUMMARY

Previous ha advanced settings could be set with

```yaml
        advanced_settings:
          das.ignoreInsufficientHbDatastore: "true"
```

but with vmware.vmware.cluster_ha it results in:

```
('The request refers to an unexpected or unknown type.', None)
```

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
ansible [core 2.17.12]
```

##### COLLECTION VERSION

```paste below
vmware.vmware             2.0.1
```

##### CONFIGURATION

```paste below
ANY_ERRORS_FATAL(./ansible.cfg) = True
CALLBACKS_ENABLED(./ansible.cfg) = ['profile_tasks']
CONFIG_FILE() = ./ansible.cfg
DEFAULT_FORKS(./ansible.cfg) = 50
DEFAULT_JINJA2_NATIVE(./ansible.cfg) = True
DEFAULT_LOAD_CALLBACK_PLUGINS(./ansible.cfg) = True
DEFAULT_STDOUT_CALLBACK(./ansible.cfg) = debug
DISPLAY_SKIPPED_HOSTS(./ansible.cfg) = False
EDITOR(env: EDITOR) = hx
HOST_KEY_CHECKING(./ansible.cfg) = True
```

##### OS / ENVIRONMENT
Arch Linux

##### STEPS TO REPRODUCE

Change from 
```yaml
    - name: Enable and configure HA
      community.vmware.vmware_cluster_ha:
        advanced_settings:
          das.ignoreInsufficientHbDatastore: "true"
          das.usedefaultisolationaddress: "false"
```
To:

```yaml
    - name: Enable and configure HA
      vmware.vmware.cluster_ha:
        advanced_settings:
          das.ignoreInsufficientHbDatastore: "true"
          das.usedefaultisolationaddress: "false"
```

I also tried:

```yaml
"das.ignoreInsufficientHbDatastore": "true"
das.ignoreInsufficientHbDatastore: true
```

##### EXPECTED RESULTS

No error in advanced_settings

##### ACTUAL RESULTS

```paste below
('The request refers to an unexpected or unknown type.', None)
```
