### ISSUE TITLE
disable proxy doesn't work

### ISSUE THREAD

**Issue by pugnacity** [ansible-collections/vmware.vmware#207]
##### SUMMARY
removing a proxy setting doesn't work

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
vmware.vmware.vcsa_setting

##### ANSIBLE VERSION

```
ansible [core 2.18.6]
  config file = /home/pugnacity/repos/project/project-ansible/ansible.cfg
  configured module search path = ['/home/pugnacity/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '/home/pugnacity/repos/project/project-ansible/modules']
  ansible python module location = /home/pugnacity/bin/ansible/lib64/python3.11/site-packages/ansible
  ansible collection location = /home/pugnacity/repos/project/project-ansible/collections:/home/pugnacity/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/pugnacity/bin/ansible/bin/ansible
  python version = 3.11.2 (main, Sep 17 2024, 03:17:19) [GCC 8.5.0 20210514 (Red Hat 8.5.0-18)] (/home/pugnacity/bin/ansible/bin/python3.11)
  jinja version = 3.1.6
  libyaml = True

```

##### COLLECTION VERSION

```paste below
# /home/pugnacity/bin/ansible/lib/python3.11/site-packages/ansible_collections
Collection    Version
------------- -------
vmware.vmware 1.11.0 

# /home/pugnacity/bin/ansible/lib64/python3.11/site-packages/ansible_collections
Collection    Version
------------- -------
vmware.vmware 1.11.0 

# /home/pugnacity/repos/project/project-ansible/collections/ansible_collections
Collection    Version
------------- -------
vmware.vmware 2.0.1  
```

##### CONFIGURATION

```paste below
CACHE_PLUGIN(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = ansible.builtin.jsonfile
CACHE_PLUGIN_CONNECTION(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = ~/.cache/facts_cache
CACHE_PLUGIN_TIMEOUT(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = 300
CALLBACKS_ENABLED(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = ['ansible.posix.profile_tasks', 'ansible.posix.timer']
COLLECTIONS_PATHS(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = ['/home/pugnacity/repos/project/project-ansible/collections', '/home/pugnacity/.ansible/collections', '/usr/share/ansible/coll>
CONFIG_FILE() = /home/pugnacity/repos/project/project-ansible/ansible.cfg
DEFAULT_FORKS(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = 50
DEFAULT_HOST_LIST(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = ['/home/pugnacity/repos/project/project-ansible/inventory/bu_81.yml']
DEFAULT_LOCAL_TMP(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = /tmp/ansible-local-676497py35afvz
DEFAULT_MODULE_PATH(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = ['/home/pugnacity/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules', '/home/pugnacity/repos/project/project-an>
DEFAULT_MODULE_UTILS_PATH(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = ['/home/pugnacity/.ansible/plugins/connection', '/usr/share/ansible/plugins/connection', '/home/pugnacity/repos/project/bc-virtua>
DEFAULT_ROLES_PATH(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = ['/home/pugnacity/repos/project/project-ansible/roles', '/home/pugnacity/.ansible/roles']
DISPLAY_SKIPPED_HOSTS(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = False
HOST_KEY_CHECKING(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = False
INTERPRETER_PYTHON(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = auto_silent
INVENTORY_CACHE_ENABLED(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = True
INVENTORY_CACHE_PLUGIN(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = jsonfile
INVENTORY_ENABLED(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = ['yaml', 'constructed', 'networktocode.nautobot.inventory']
TASK_TIMEOUT(/home/pugnacity/repos/project/project-ansible/ansible.cfg) = 180
```

##### STEPS TO REPRODUCE
Have a vCenter with configured proxy server and you want to remove the proxy settings with the following tasks

```yaml
    - name: Configure vcenter | vCenter appliance proxy
      vmware.vmware.vcsa_settings:
        hostname: "{{ inventory_hostname }}"
        username: "{{ vcenter_default_secret['user'] }}@{{ vmware_vcenter_domain_name }}"
        password: "{{ vcenter_default_secret['password'] }}"
        validate_certs: "{{ validate_certificate }}"
        proxy:
          - enabled: false
            protocol: https
            url: "http://{{ proxy.server }}"
            port: "{{ proxy.port }}"
          - enabled: false
            protocol: http
            url: "http://{{ proxy.server }}"
            port: "{{ proxy.port }}"
          - enabled: false
            protocol: ftp
            url: "http://{{ proxy.server }}"
            port: "{{ proxy.port }}"
        noproxy: "{{ proxy.noproxy }}"
      delegate_to: localhost
      register: _vcenter_request
      until: _vcenter_request is succeeded
      retries: "{{ retries_settings['number'] }}"
      delay: "{{ retries_settings['delay'] }}"
      when:
        - vcenter_configure_proxy

```

##### EXPECTED RESULTS
proxy is removed

##### ACTUAL RESULTS
nothing has been changed

```paste below
TASK [Configure vcenter | vCenter appliance proxy] *************************************************************************************************************************************************************************************************************
task path: /home/winsv01-ext/repos/project/project-ansible/playbooks/11_configure_vcenter.yml:127
ok: [vcenter.company.tld -> localhost] => {
    "attempts": 1,
    "changed": false,
    "invocation": {
        "module_args": {
            "consolecli_enabled": null,
            "dcui_enabled": null,
            "dns_append": true,
            "dns_domains": null,
            "dns_hostname": null,
            "dns_mode": null,
            "dns_servers": null,
            "firewall_rules": null,
            "firewall_rules_append": true,
            "global_fips": null,
            "hostname": "vcenter.company.tld",
            "noproxy": [
                "company.tld"
            ],
            "ntp_servers": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "proxy": [
                {
                    "enabled": false,
                    "password": null,
                    "port": 3128,
                    "protocol": "https",
                    "url": "http://proxy.company.tld",
                    "username": null
                },
                {
                    "enabled": false,
                    "password": null,
                    "port": 3128,
                    "protocol": "http",
                    "url": "http://proxy.company.tld",
                    "username": null
                },
                {
                    "enabled": false,
                    "password": null,
                    "port": 3128,
                    "protocol": "ftp",
                    "url": "http://proxy.company.tld",
                    "username": null
                }
            ],
            "proxy_host": null,
            "proxy_port": null,
            "proxy_protocol": "https",
            "resize_storage": false,
            "shell_enabled": null,
            "shell_timeout": null,
            "ssh_enabled": null,
            "timesync_mode": null,
            "timezone": null,
            "username": "administrator@comp.local",
            "validate_certs": false
        }
    },
    "vcsa": {
        "hostname": "vcenter.company.tld",
        "port": 443
    },
    "vcsa_settings": {
        "dns_mode": null,
        "noproxy": [
            "company.tld"
        ],
        "proxy": [
            {
                "enabled": false,
                "password": null,
                "port": 3128,
                "protocol": "https",
                "url": "http://proxy.company.tld",
                "username": null
            },
            {
                "enabled": false,
                "password": null,
                "port": 3128,
                "protocol": "http",
                "url": "http://proxy.company.tld",
                "username": null
            },
            {
                "enabled": false,
                "password": null,
                "port": 3128,
                "protocol": "ftp",
                "url": "http://proxy.company.tld",
                "username": null
            }
        ],
        "resize_storage": false
    }
}

```
